# Project Name
TARGET = DemoGFX2

# Sources
CPP_SOURCES = DemoGFX2.cpp ../DaisySeedGFX2/cDisplay.cpp ../DaisySeedGFX2/GFX.cpp ../DaisySeedGFX2/TFT_SPI.cpp

# Library Locations
LIBDAISY_DIR = ../LibDaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
